#! /bin/sh
#
# Example panel for LemonBoy's bar

dir=$(dirname $0)
source $dir/scripts/config

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		D*)
			# datetime output
			datetime="%{F$COLOR_TITLE_FG} ${line#?} %{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_STATUS_FG} ${line#?} %{F-}"
			;;
		B*)
			# battery output
			battery="%{F$COLOR_STATUS_FG} ${line#?} %{F-}"
			;;
		P*)
			# wifi output
			wifi="%{F$COLOR_STATUS_FG} ${line#?} %{F-}"
			;;
		V*)
			# volume output
			volume="%{F$COLOR_STATUS_FG} ${line#?} %{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG} $FULL_CIRCLE%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG} $EMPTY_CIRCLE%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG} $FULL_CIRCLE%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG} $FULL_CIRCLE%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG} $EMPTY_CIRCLE%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG} $FULL_CIRCLE%{F-}"
						;;
					#L*)
					#	# layout
					#	wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}${name} %{F-}"
					#	;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm_infos} ${title}%{c}${datetime}%{r}${volume} ${battery} ${wifi}"
done
